kafka:
  common:
    bootstrapServers: localhost:9092
    pingApplicationId: "ping-app"
    pongApplicationId: "pong-app"
    groupId: "ping-pong-group-1"
    serializer: "org.apache.kafka.common.serialization.StringSerializer"
    deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    offsetReset: "latest"
  topics:
    gameTopic: "ping_pong"
  messages:
    teamOneLogMessage: "Mr. Ping returns the pong with a ping!"
    teamOnePayload: "ping!"
    teamTwoLogMessage: "Mr. Pong returns the ping with a pong!"
    teamTwoPayload: "pong!"
teams:
  teamOne: "Ping"
  teamTwo: "Pong"